name: Pantheon - Delete Multidev Environment

on:
  delete

jobs:
  delete_multidev:
    name: Pantheon - Delete Multidev Environment
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'feature/multidev/')
    steps:
      - name: Set Multidev Environment Name
        shell: bash
        id: multidev-env
        env:
          EVENT_REF: ${{ github.event.ref }}
        run: echo "name=$(echo ${EVENT_REF} | cut -d '/' -f3)" >> $GITHUB_OUTPUT

      - name: Pantheon Delete Multidev Environment
        uses: padillaco/pantheon-multidev-action@main
        with:
          pantheon_site_slug: [pantheon-site-slug]
          pantheon_machine_token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
          multidev_env_name: ${{ steps.multidev-env.outputs.name }}
          action: delete
