name: Pantheon - Create Multidev Environment

on:
  create

jobs:
  create_multidev:
    name: Pantheon - Create Multidev Environment
    runs-on: ubuntu-latest
    if: startsWith(github.ref_name, 'feature/multidev/')
    steps:
      - name: Set Multidev Environment Name
        shell: bash
        id: multidev-env
        run: echo "name=$(echo ${GITHUB_REF_NAME} | cut -d '/' -f3)" >> $GITHUB_OUTPUT

      - name: Pantheon Create Multidev Environment
        uses: padillaco/pantheon-multidev-action@main
        with:
          pantheon_site_slug: [pantheon-site-slug]
          pantheon_machine_token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
          multidev_env_name: ${{ steps.multidev-env.outputs.name }}
          action: create

      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Build and Deploy
        uses: ./.github/actions/build-and-deploy
        with:
          # SSH private key to use for remote repository authentication
          ssh_private_key: ${{ secrets.PANTHEON_SSH_PRIVATE_KEY }}
