name: 'Deploy to Remote Repository'
description: 'Uses rsync and GIT to deploy files from a GitHub repository to a remote repository.'
author: 'padillaco'
branding:
  icon: 'cloud-lightning'
  color: 'blue'
inputs:
  base_directory:
    description: 'Base directory for rsync'
    required: false
    default: '.'
  destination_directory:
    description: 'Destination directory for rsync in remote repository'
    required: false
    default: '.'
  exclude_list:
    description: 'Comma-separated list of files and directories to exclude from sync'
    required: false
    default: '.git, .github, .gitmodules, node_modules'
  ssh_private_key:
    description: 'SSH private key to use for remote repository authentication'
    required: true
  remote_repo:
    description: 'Remote repository URL'
    required: true
  remote_branch:
    description: 'Remote branch to clone and push'
    required: false
  force_push:
    description: 'Force push the latest commit'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Install rsync
      run: sudo apt-get install -y rsync
      shell: bash
    
    - id: Push to Remote Repository
      env:
        BASE_DIRECTORY: ${{ inputs.base_directory }}
        DESTINATION_DIRECTORY: ${{ inputs.destination_directory }}
        EXCLUDE_LIST: ${{ inputs.exclude_list }}
        GIT_SSH_COMMAND: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ~/.ssh/private_key
        REMOTE_REPO: ${{ inputs.remote_repo }}
        REMOTE_REPO_DIR: /tmp/remote_repo
        REMOTE_BRANCH: ${{ inputs.remote_branch != '' && inputs.remote_branch || github.ref_name }}
        SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
        FORCE_PUSH: ${{ inputs.force_push }}
      run: ${{ github.action_path }}/run.sh
      shell: bash
